' Gambas module file

Public ClosedMini As Boolean = False

Public Loaded As Boolean = False

Public AppPath As String = ""
Public HomePath As String = ""

'Data Form Stuff
Public DataItemsRows As Long = -1

'Theme Stuff
Public ThemeName As String = ""
Public Wallpaper As Picture
Public Screenshot As Picture = New Picture
Public Icon As Picture
Public StartButton As Picture

'Scale Variables
Public ScaleX As Float = 0
Public ScaleY As Float = 0


'Original Form Size
Public OrigFormWidth As Long = 0
Public OrigFormHeight As Long = 0

Public OrigCatLeft As Long = 0
Public OrigCatTop As Long = 0
Public OrigCatWidth As Long = 0
Public OrigCatHeight As Long = 0

Public OrigItemLeft As Long = 0
Public OrigItemTop As Long = 0
Public OrigItemWidth As Long = 0
Public OrigItemHeight As Long = 0

Public OrigScreenLeft As Long = 0
Public OrigScreenTop As Long = 0
Public OrigScreenWidth As Long = 0
Public OrigScreenHeight As Long = 0
