' Gambas module file

Public HideOnline As Boolean

Public QuitOnComplete As Boolean
Public UseOnlineRepository As Boolean = True ' Default to using online repo
Public UseCacheRepository As Boolean = True
Public UseLocalDBFiles As Boolean = True
Public UseVideoPlayback As Boolean = True
Public VideoVolume As Float = 0.2 '20%

Public ClosedMini As Boolean = False

Public Loaded As Boolean = False

Public AppPath As String = ""
Public HomePath As String = ""

'Data Form Stuff
Public DataItemsRows As Long = -1

'Theme Stuff
Public ThemeName As String = ""
Public Wallpaper As Picture
Public Screenshot As Picture = New Picture
Public Icon As Picture
Public StartButton As Picture

Public SetTitleCol As Integer = &hFFFFFF
Public SetCategoryCol As Integer = &hFFFFFF
Public SetDescriptionCol As Integer = &hFFFFFF
Public SetItemCol As Integer = &hFFFFFF
Public SetItemColssApp As Integer = &hFFFFFF
Public SetItemColppApp As Integer = &hFFFF50
Public SetItemColppGame As Integer = &hAAFF40
Public SetItemColLLApp As Integer = &h80B0FF
Public SetItemColLLGame As Integer = &hff55ff
Public SetStatsCol As Integer = &hFFFFFF
Public SetMetaCol As Integer = &hFFFFFF
Public SetBGCol As Integer = &h202020
Public SetFGCol As Integer = &hFFFFFF
Public SetSelectCol As Integer = &h2a4aaa
Public SetLoadingCol As Integer = &hFFFFFF

Public SetTitleFont As String = "Ubuntu"
Public SetListFont As String = "Ubuntu"
Public SetDescriptionFont As String = "Ubuntu"
Public SetStatsFont As String = "Ubuntu"
Public SetMetaFont As String = "Ubuntu"
Public SetLoadingFont As String = "Ubuntu"

Public SetTitlesBold As Boolean = True
Public SetListBold As Boolean = False
Public SetDescriptionBold As Boolean = False


'Scale Variables
Public ScaleX As Float = 0
Public ScaleY As Float = 0


'Original Form Size
Public OrigFormWidth As Long = 0
Public OrigFormHeight As Long = 0

Public OrigCatLeft As Long = 0
Public OrigCatTop As Long = 0
Public OrigCatWidth As Long = 0
Public OrigCatHeight As Long = 0

Public OrigItemLeft As Long = 0
Public OrigItemTop As Long = 0
Public OrigItemWidth As Long = 0
Public OrigItemHeight As Long = 0

Public OrigScreenLeft As Long = 0
Public OrigScreenTop As Long = 0
Public OrigScreenWidth As Long = 0
Public OrigScreenHeight As Long = 0
