#!/bin/bash

files=$(echo $NEMO_SCRIPT_SELECTED_URIS | sed -e 's/file:\/\///g' -e 's/\%20/\ /g')

Pat="Z:$files"

echo cd \"$HOME/.wine/dosdevices/c:\" >"$HOME/.setups"
echo cd \"Program Files/SetupS.SendTo/ssEditor\" >>"$HOME/.setups"
echo "echo Opening with SetupS Editor..." >>"$HOME/.setups"
echo wine ./ssEditor.exe "\"$Pat"\" 2\>/dev/null >>"$HOME/.setups"
chmod +x "$HOME/.setups"
gnome-terminal -e "$HOME/.setups"
rm "$HOME/.setups"
