#!/usr/bin/env bash
zenity --question --text="Create an ISO image here?" || exit

(mkisofs -r -o "$*".iso "$*" 2>&1 |
while read i; do
	PARCIAL=$(echo $i | grep -o [0-9]*'\.'[0-9]*)
	if [ $PARCIAL ]; then
		echo $PARCIAL
		echo "# $PARCIAL% done..."
	fi;
done
echo "# Finish." ) | zenity --progress --title="Creating \"$*.iso\""
